Author: HC

version: 0.1

last modifs : 07/07/2025

# Library Import

In [1]:
import pandas as pd
import numpy as np
import os
import glob
import re

# Def parameters

In [2]:
ZT0 = "7:00:00 AM"

dir_input = 'D:\Temp\Sleep_recordings'

annot_dict = {
    "6-16-2025" : "NS",
    "6-27-2025" : "SDW1",
    "7-4-2025" : "SDW2",
    "7-11-2025" : "SDW3"
}

if not os.path.exists(f'{dir_input}/output/'):
    output_dir = os.mkdir(f'{dir_input}/output/')

# Def function

In [ ]:
def separate_days(dir_input, ZT0, annot_dict = annot_dict):
    list_files = glob.glob(dir_input + '/' + '*_whole-recording.csv')
    output_dir = f'{dir_input}/output'

    if len(list_files) == 0:
        print('No file matching expected format found, please double check files name ("ID_{mouseIDorwhatever}_whole-recording.csv") and input pathway.')

    for n, file in enumerate(list_files):
        sample = re.split("_", list_files[n])[-2]

        print(f"Start processing of {sample} recording")
        
        df = pd.read_csv(file)
        df.drop(labels=0, axis=0,inplace=True) ## Remove units
        df = df.reset_index()
        if df.columns[-1] != 'Activity':
            df.drop(labels=df.columns[-1],axis=1,inplace=True)
        if df.columns[0] == 'index':
            df.drop(labels=df.columns[0],axis=1,inplace=True)
        
        unique_dates = df['Time Stamp'].apply(lambda x : x.split(' ')[0])
        unique_dates = unique_dates.unique().astype(str)
        unique_dates_noslash = np.char.replace(unique_dates, "/","-") ## For new filename

        list_pos_CT0 = {}
        for n, date in enumerate(unique_dates):
            print(n, date)
            nex = n+1
            if n==0:
                debut = 0
                temp_position = df[df['Time Stamp']==f'{unique_dates[nex]} {ZT0}'].index[0] - 1
            elif n == len(unique_dates) - 1 :
                debut = df[df['Time Stamp']==f'{unique_dates[n]} {ZT0}'].index[0]
                temp_position = len(df)
            else:
                debut = df[df['Time Stamp']==f'{unique_dates[n]} {ZT0}'].index[0]
                temp_position = df[df['Time Stamp']==f'{unique_dates[nex]} {ZT0}'].index[0] - 1

            list_pos_CT0[unique_dates[n]] = (debut,temp_position)

        list_pos_CT0

        exp_df = pd.DataFrame(data = {"Date" : unique_dates_noslash,
                              "Expe": np.zeros(len(unique_dates))})
        
        if len(annot_dict) > 0:
            current_exp = ["Undefined"]
            # print(annot_dict)
            for n, date in enumerate(exp_df['Date'].unique()):
                # print(n, date)
                if date in annot_dict.keys():
                    current_exp = annot_dict[date]
                exp_df.loc[n,"Expe"] = current_exp


        pd.options.mode.copy_on_write = True
        for n, key in enumerate(list_pos_CT0.keys()):
            df_temp = df[list_pos_CT0[key][0]:list_pos_CT0[key][1]]
            df_temp.dropna(thresh= 2, axis=0, inplace= True)
            # print(len(df_temp))
            if len(df_temp) > 1:
                if len(annot_dict) > 0:
                    df_temp.to_csv(f'{dir_input}\output\{exp_df.loc[n,"Date"]}_{sample}-{exp_df.loc[n,"Expe"]}.csv',index=None)
                else:
                    df_temp.to_csv(f'{dir_input}\output\{exp_df.loc[n,"Date"]}_{sample}.csv',index=None)

# Run function

In [4]:
separate_days(dir_input = dir_input,
              ZT0 = ZT0,
            #   annot_dict = annot_dict
              )

Start processing of 1238359 recording

C:\Users\hcall\AppData\Local\Temp\ipykernel_6012\1817514227.py:13: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

0 6/16/2025
1 6/17/2025
2 6/18/2025
3 6/19/2025
4 6/20/2025
5 6/21/2025
6 6/22/2025
7 6/23/2025
8 6/24/2025
9 6/25/2025
10 6/26/2025
11 6/27/2025
12 6/28/2025
13 6/29/2025
14 6/30/2025
15 7/1/2025
16 7/2/2025
17 7/3/2025
18 7/4/2025
19 7/5/2025
20 7/6/2025
21 7/7/2025
{'6-16-2025': 'NS', '6-27-2025': 'SDW1', '7-4-2025': 'SDW2', '7-11-2025': 'SDW3'}
Start processing of 1267840 recording

C:\Users\hcall\AppData\Local\Temp\ipykernel_6012\1817514227.py:13: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

0 6/16/2025
1 6/17/2025
2 6/18/2025
3 6/19/2025
4 6/20/2025
{'6-16-2025': 'NS', '6-27-2025': 'SDW1', '7-4-2025': 'SDW2', '7-11-2025': 'SDW3'}
Start processing of 1267843 recording

C:\Users\hcall\AppData\Local\Temp\ipykernel_6012\1817514227.py:13: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

0 6/16/2025
1 6/17/2025
2 6/18/2025
3 6/19/2025
4 6/20/2025
5 6/21/2025
6 6/22/2025
7 6/23/2025
8 6/24/2025
9 6/25/2025
10 6/26/2025
11 6/27/2025
12 6/28/2025
13 6/29/2025
14 6/30/2025
15 7/1/2025
16 7/2/2025
17 7/3/2025
18 7/4/2025
19 7/5/2025
20 7/6/2025
21 7/7/2025
{'6-16-2025': 'NS', '6-27-2025': 'SDW1', '7-4-2025': 'SDW2', '7-11-2025': 'SDW3'}
Start processing of 1269984 recording

C:\Users\hcall\AppData\Local\Temp\ipykernel_6012\1817514227.py:13: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

0 6/16/2025
1 6/17/2025
2 6/18/2025
3 6/19/2025
4 6/20/2025
5 6/21/2025
6 6/22/2025
7 6/23/2025
8 6/24/2025
9 6/25/2025
10 6/26/2025
11 6/27/2025
12 6/28/2025
13 6/29/2025
14 6/30/2025
15 7/1/2025
16 7/2/2025
17 7/3/2025
18 7/4/2025
19 7/5/2025
20 7/6/2025
21 7/7/2025
{'6-16-2025': 'NS', '6-27-2025': 'SDW1', '7-4-2025': 'SDW2', '7-11-2025': 'SDW3'}

# Debugging only, please ignore.

In [20]:
df = pd.read_csv(f'{dir_input}\ID_1267843_whole-recording.csv')

df.drop(labels=0, axis=0,inplace=True) ## Remove units
df = df.reset_index()
if df.columns[-1] != 'Activity':
    df.drop(labels=df.columns[-1],axis=1,inplace=True)
if df.columns[0] == 'index':
    df.drop(labels=df.columns[0],axis=1,inplace=True)

unique_dates = df['Time Stamp'].apply(lambda x : x.split(' ')[0])
unique_dates = unique_dates.unique().astype(str)
unique_dates_noslash = np.char.replace(unique_dates, "/","-") ## For new filename

C:\Users\hcall\AppData\Local\Temp\ipykernel_17600\3991956325.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f'{dir_input}\ID_1267843_whole-recording.csv')

In [ ]:
df

,Time Stamp,EMG,Delta,Theta,Alpha,Sigma,Beta,EEG,Temp,Activity
0,6/16/2025 5:05:14 PM,7.474e-06,0.2932,0.3959,0.1185,0.05999,0.1283,2.291e-09,37.31,0.001984
1,6/16/2025 5:05:16 PM,9.105e-06,0.2581,0.2933,0.1934,0.1133,0.1356,2.268e-09,37.32,0.001984
2,6/16/2025 5:05:18 PM,6.785e-06,0.222,0.56,0.09631,0.02579,0.0894,4.151e-09,37.32,0.001984
3,6/16/2025 5:05:20 PM,6.636e-06,0.2405,0.3282,0.2126,0.05966,0.1523,2.842e-09,37.32,0.001984
4,6/16/2025 5:05:22 PM,6.637e-06,0.2978,0.3414,0.1844,0.08251,0.09192,2.94e-09,37.32,0.001984
...,...,...,...,...,...,...,...,...,...,...
893922,7/7/2025 9:42:38 AM,0.000014,0.2639,0.315,0.2142,0.04241,0.1487,0.0,34.33,0.001984
893923,7/7/2025 9:42:40 AM,0.000018,0.3857,0.1517,0.166,0.151,0.1297,0.0,34.33,0.001984
893924,7/7/2025 9:42:42 AM,0.000012,0.3717,0.3877,0.09027,0.04296,0.09575,0.0,34.36,0.001984
893925,7/7/2025 9:42:44 AM,0.000008,0.2637,0.3939,0.1558,0.06292,0.1082,0.0,34.34,0.001984
893926,7/7/2025 9:42:46 AM,0.00002,0.4371,0.2803,0.1655,0.06799,0.04206,0.0,34.33,0.001984

In [21]:
list_pos_CT0 = {}
for n, date in enumerate(unique_dates):
    print(n, date)
    nex = n+1
    if n==0:
        debut = 0
        temp_position = df[df['Time Stamp']==f'{unique_dates[nex]} {ZT0}'].index[0] - 1
    elif n == len(unique_dates) - 1 :
        debut = df[df['Time Stamp']==f'{unique_dates[n]} {ZT0}'].index[0]
        temp_position = len(df)
    else:
        debut = df[df['Time Stamp']==f'{unique_dates[n]} {ZT0}'].index[0]
        temp_position = df[df['Time Stamp']==f'{unique_dates[nex]} {ZT0}'].index[0] - 1

    list_pos_CT0[unique_dates[n]] = (debut,temp_position)

list_pos_CT0

0 6/16/2025
1 6/17/2025
2 6/18/2025
3 6/19/2025
4 6/20/2025
5 6/21/2025
6 6/22/2025
7 6/23/2025
8 6/24/2025
9 6/25/2025
10 6/26/2025
11 6/27/2025
12 6/28/2025
13 6/29/2025
14 6/30/2025
15 7/1/2025
16 7/2/2025
17 7/3/2025
18 7/4/2025
19 7/5/2025
20 7/6/2025
21 7/7/2025

{'6/16/2025': (0, 25042),
 '6/17/2025': (25043, 68242),
 '6/18/2025': (68243, 111442),
 '6/19/2025': (111443, 154642),
 '6/20/2025': (154643, 197842),
 '6/21/2025': (197843, 241042),
 '6/22/2025': (241043, 284242),
 '6/23/2025': (284243, 327442),
 '6/24/2025': (327443, 370642),
 '6/25/2025': (370643, 413842),
 '6/26/2025': (413843, 457042),
 '6/27/2025': (457043, 500242),
 '6/28/2025': (500243, 543442),
 '6/29/2025': (543443, 586642),
 '6/30/2025': (586643, 629842),
 '7/1/2025': (629843, 673042),
 '7/2/2025': (673043, 716242),
 '7/3/2025': (716243, 759442),
 '7/4/2025': (759443, 802642),
 '7/5/2025': (802643, 845842),
 '7/6/2025': (845843, 889042),
 '7/7/2025': (889043, 893927)}

In [ ]:
df[df['Time Stamp']==f'{unique_dates[nex]} {ZT0}'].index

Index([], dtype='int64')

In [ ]:
annot_dict = {
    "6-16-2025" : "NS",
    "6-27-2025" : "SDW1",
    "7-4-2025" : "SDW2",
    "7-11-2025" : "SDW3"
}

In [10]:
current_exp = ["Undefined"]
current_exp = annot_dict['06-16-2025']
current_exp

'NS'

In [16]:
annot_df = pd.DataFrame(data= {"Date" : annot_dict.keys(),
                               "Exp" : annot_dict.values()})
print(annot_df)
# unique_dates

Empty DataFrame
Columns: [Date, Exp]
Index: []

In [22]:
exp_df = pd.DataFrame(data = {"Date" : unique_dates,
                              "Expe": np.zeros(len(unique_dates))})
exp_df

         Date  Expe
0   6/16/2025   0.0
1   6/17/2025   0.0
2   6/18/2025   0.0
3   6/19/2025   0.0
4   6/20/2025   0.0
5   6/21/2025   0.0
6   6/22/2025   0.0
7   6/23/2025   0.0
8   6/24/2025   0.0
9   6/25/2025   0.0
10  6/26/2025   0.0
11  6/27/2025   0.0
12  6/28/2025   0.0
13  6/29/2025   0.0
14  6/30/2025   0.0
15   7/1/2025   0.0
16   7/2/2025   0.0
17   7/3/2025   0.0
18   7/4/2025   0.0
19   7/5/2025   0.0
20   7/6/2025   0.0
21   7/7/2025   0.0

In [24]:
len(annot_dict)

0

In [23]:
current_exp = []
for n, date in enumerate(exp_df['Date'].unique()):
    # print(n, date)
    if date in annot_dict.keys():
        current_exp = annot_dict[date]
    exp_df.loc[n,"Expe"] = current_exp

exp_df

ValueError: Must have equal len keys and value when setting with an iterable

In [ ]:
sample = "test"

In [ ]:
unique_dates_noslash2

In [ ]:
pd.options.mode.copy_on_write = True
for n, key in enumerate(list_pos_CT0.keys()):
    df_temp = df[list_pos_CT0[key][0]:list_pos_CT0[key][1]]
    df_temp.dropna(thresh= 2, axis=0, inplace= True)
    # print(len(df_temp))
    if len(df_temp) > 1:
        df_temp.to_csv(f'{dir_input}\output\{exp_df.loc[n,"Date"]}_{sample}-{exp_df.loc[n,"Expe"]}.csv',index=None)

In [ ]:
unique_dates_noslash

array(['6-16-2025', '6-17-2025', '6-18-2025', '6-19-2025', '6-20-2025',
       '6-21-2025', '6-22-2025', '6-23-2025', '6-24-2025', '6-25-2025',
       '6-26-2025', '6-27-2025', '6-28-2025', '6-29-2025', '6-30-2025',
       '7-1-2025', '7-2-2025', '7-3-2025', '7-4-2025', '7-5-2025',
       '7-6-2025', '7-7-2025'], dtype='<U9')